import Link from "next/link";
import { Footer } from "@/components/Footer";

export default function TermsPage() {
  return (
    <main>
      <section className="px-6 py-20 max-w-3xl mx-auto">
        <Link href="/" className="text-text-secondary hover:text-text-primary text-sm mb-8 inline-block">
          ← Back to Home
        </Link>
        <h1 className="font-[family-name:var(--font-heading)] text-3xl md:text-4xl font-bold mb-8">
          Terms of Service
        </h1>
        <div className="glass-card p-8 md:p-12 text-text-secondary leading-relaxed space-y-6">
          <p><strong className="text-text-primary">Last Updated:</strong> March 2026</p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Entertainment Purposes</h2>
          <p>
            All readings provided by Luna AI Celestial Readings are for entertainment and self-reflection purposes only. Our readings do not constitute professional advice of any kind, including but not limited to medical, legal, financial, or psychological advice. Always consult qualified professionals for important life decisions.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">AI-Generated Content</h2>
          <p>
            All readings are generated by artificial intelligence. While we use real astrological frameworks and your actual birth data, the interpretations are AI-generated. We do not guarantee the accuracy, completeness, or applicability of any reading.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Refund Policy</h2>
          <p>
            Due to the digital nature of our readings, all purchases are final and non-refundable. Your reading is generated and delivered instantly upon payment. If you experience a technical issue preventing delivery of your reading, please contact us and we will resolve the issue.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Age Requirement</h2>
          <p>
            You must be at least 18 years of age to use our services and make purchases.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Intellectual Property</h2>
          <p>
            All content, branding, and generated readings are the intellectual property of Luna AI Celestial Readings and Velora Crystal. You may save and share your personal reading for non-commercial purposes. Systematic copying, redistribution, or resale of readings is prohibited.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Limitation of Liability</h2>
          <p>
            Luna AI Celestial Readings and Velora Crystal shall not be liable for any decisions made based on the content of our readings. You acknowledge that astrology is a belief system and use our services at your own discretion.
          </p>

          <h2 className="font-[family-name:var(--font-heading)] text-xl text-text-primary mt-6">Contact</h2>
          <p>
            For questions about these terms, please contact us at{" "}
            <a href="mailto:veloracrystal.official@gmail.com" className="text-purple-light hover:text-text-primary underline">
              veloracrystal.official@gmail.com
            </a>.
          </p>
        </div>
      </section>
      <Footer />
    </main>
  );
}
